version: 2.1

workflows:
  check_website:
    triggers:
      - schedule:
          cron: "0,10,20,30,40,50 * * * *"
          filters:
            branches:
              only: circleci-project-setup
    jobs:
      - check_site

jobs:
  check_site:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Check website updates
          command: |
            TZ=Asia/Tokyo
            echo "CURRENT_DATE=$(date '+%Y-%m-%d')" >> $GITHUB_ENV

            curl -sL https://www.elegaku.com/cast/schedule/castCode/329878 > website.html

            if [ -f website_previous.html ]; then
              if diff -B website_previous.html website.html | grep 'class.*' >/dev/null; then
                echo "Changes found"
                curl -H "Content-Type: application/json" \
                 -X POST \
                 -d '{"content": "update web"}' \
                 https://discord.com/api/webhooks/1367284131909734524/rlj6EN4ti6pgYALxaahl3OTcp5qfjNlUCLH052OYzKHI3J59Inn0bvpNOl6w0ggpPkex
              else
                echo "No changes detected."
              fi
            fi
            mv website.html website_previous.html

            git config --global user.email "GitHubActions@example.com"
            git config --global user.name "GitHub Actions"

            git add .
            git commit -m "Automated commit from GitHub Actions"
            git push origin main

            
