version: 2.1

workflows:
  check_website:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only: circleci-project-setup
    jobs:
      - check_site

jobs:
  check_site:
    docker:
      - image: cimg/python:3.13.3
    steps:
      - checkout
      - run:
          name: Check website updates
          command: |
            TZ=Asia/Tokyo
            echo "CURRENT_DATE=$(date '+%Y-%m-%d')"
            
            pwd
            ls -l
            
            chown -R $USER:$USER /home/circleci/project
            curl -sL https://www.elegaku.com/cast/schedule/castCode/161731 > website.html

            if [ -f website_previous.html ]; then

              echo "DIFF Start"
              set +e
              DIFF_FILES=$( diff –new-line-format website_previous.html website.html | grep 'class.*' )
              set -e
              echo "DIFF END"
              
              echo "$DIFF_FILES"

              if [ -n "$DIFF_FILES" ]; then
              
                echo "Changes found"
                
                curl -H "Content-Type: application/json" \
                 -X POST \
                 -d '{"content": "${DIFF_FILES} \n https://www.elegaku.com/cast/schedule/castCode/161731"}' \
                 https://discord.com/api/webhooks/1367284131909734524/rlj6EN4ti6pgYALxaahl3OTcp5qfjNlUCLH052OYzKHI3J59Inn0bvpNOl6w0ggpPkex
              else
                echo "No changes detected."
              fi
            fi
            mv website.html website_previous.html

            echo "git add"
            git config --global user.email "circleci@example.com"
            git config --global user.name "circleci Actions"

            git add .
            git commit -m "Automated commit from circleci Actions"
            git push origin circleci-project-setup

            
