name: Monitor Website

on:
  schedule:
    - cron: '*/5 23 * * *'    # 5分ごとに実行 (日本時間 8:00)
    - cron: '*/5 0-11 * * *'  # 5分ごとに実行 (日本時間 9:00～20:00)
    # - cron: '*/5 8-20 * * *'  # 10分ごとに実行
  workflow_dispatch:

jobs:
  check_website:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Set Current Date
        run: |
          TZ=Asia/Tokyo
          echo "CURRENT_DATE=$(date '+%Y-%m-%d')" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest workflow run ID
        run: |
          pwd
          gh auth status
          RUN_ID=$(gh run list --limit 1 --json databaseId --jq ".[0].databaseId") >> $GITHUB_ENV
          echo $RUN_ID
        #  gh run download $(gh run list --limit 1 --json databaseId --jq ".[0].databaseId")
        #  gh run download $RUN_ID --repo Migratory-Birds/WEB-Update-Notification
        # curl https://github.com/Migratory-Birds/WEB-Update-Notification/actions/runs/14789915795/artifacts/3048918668
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Fetch Website Content
        # run: curl -sL https://www.elegaku.com/cast/schedule/castCode/352662 > website.html
        run: |
          curl -sL https://www.elegaku.com/cast/schedule/castCode/369180 > website.html

      - name: Compare with Previous Version
        run: |
          echo 100
          if [ -f website_previous.html ]; then
            echo 200
            diff -B website_previous.html website.html | grep 'class.*'
            echo 201
            
            if diff -B website_previous.html website.html | grep 'class.*' >/dev/null; then
              echo 300
              echo "No changes detected."
            else
              echo 400
              echo "Changes found, taking action..."
              curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "update"}' \
               https://discord.com/api/webhooks/1367284131909734524/rlj6EN4ti6pgYALxaahl3OTcp5qfjNlUCLH052OYzKHI3J59Inn0bvpNOl6w0ggpPkex
            fi
          fi

          mv website.html website_previous.html
          git config --global user.email "GitHubActions@example.com"
          git config --global user.name "GitHub Actions"

          git add .
          git commit -m "Automated commit from GitHub Actions"
          git push origin main

