name: Monitor Website

on:
  schedule:
    - cron: '*/10 * * * *'  # 10分ごとに実行

jobs:
  check_website:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout repository
      #  uses: actions/checkout@v3

      - name: Fetch Website Content
        run: curl -sL hhttps://www.elegaku.com/profile/top/castCode/329878/ > website.html

      - name: Compare with Previous Version
        run: |
          if [ -f website_previous.html ]; then
            diff website_previous.html website.html || echo "Website updated!"
            curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "Webサイトに変更が検出されました！"}' \
               https://discord.com/api/webhooks/1367284131909734524/rlj6EN4ti6pgYALxaahl3OTcp5qfjNlUCLH052OYzKHI3J59Inn0bvpNOl6w0ggpPkex
          fi
          mv website.html website_previous.html