name: Monitor Website

on:
  schedule:
    - cron: '*/5 23 * * *'    # 5分ごとに実行 (日本時間 8:00)
    - cron: '*/5 0-11 * * *'  # 5分ごとに実行 (日本時間 9:00～20:00)
    # - cron: '*/5 8-20 * * *'  # 10分ごとに実行
  workflow_dispatch:

jobs:
  check_website:
    runs-on: ubuntu-latest
    steps:

      - name: Set Current Date
        run: |
          TZ=Asia/Tokyo
          echo "CURRENT_DATE=$(date '+%Y-%m-%d')"

      - name: Download HTML
        uses: actions/download-artifact@v4
        with: 
          name: website_previous.html
        continue-on-error: true

      - name: Fetch Website Content
        # run: curl -sL https://www.elegaku.com/cast/schedule/castCode/329878 > website.html
        run: curl -sL https://www.elegaku.com/cast/schedule/castCode/369180 > website.html

      - name: Compare with Previous Version
        run: |
          if [ -f website_previous.html ]; then
            diff website_previous.html website.html || curl -H "Content-Type: application/json" \
               -X POST \
               -d "a{\"content\": \"nishimura - update\"}" \
               https://discord.com/api/webhooks/1367284131909734524/rlj6EN4ti6pgYALxaahl3OTcp5qfjNlUCLH052OYzKHI3J59Inn0bvpNOl6w0ggpPkex
          fi

      - name: Upload HTML
        uses: actions/upload-artifact@v4
        with: 
          name: website_previous.html
          path: website.html
